// Auto-generated. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

public static class AnimStateNameLookUp
{
   public static Dictionary<int, string> names = new()
   {
      { Animator.StringToHash("Base Layer.Climb_Rope_With_Legs"), "Climb_Rope_With_Legs" },
      { Animator.StringToHash("Base Layer.Idle"), "Idle" },
      { Animator.StringToHash("Base Layer.FrontWall"), "FrontWall" },
      { Animator.StringToHash("Base Layer.Ladder.Traversal_Ladder_Climb_Up_Loop"), "Traversal_Ladder_Climb_Up_Loop" },
      { Animator.StringToHash("Base Layer.Ladder.Traversal_Ladder_Climb_Down_Start"), "Traversal_Ladder_Climb_Down_Start" },
      { Animator.StringToHash("Base Layer.Ladder.EndToPlatform"), "EndToPlatform" },
      { Animator.StringToHash("Base Layer.Ladder.EndToPlatfor Settle"), "EndToPlatfor_Settle" },
      { Animator.StringToHash("Base Layer.Ladder.Ladder_ClimbUp"), "Ladder_ClimbUp" },
      { Animator.StringToHash("Base Layer.Ladder.Ladder_Start_From_Top"), "Ladder_Start_From_Top" },
      { Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_L"), "Ladder_Look_Back_L" },
      { Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_R"), "Ladder_Look_Back_R" },
      { Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_To_Jump_L"), "Ladder_Look_Back_To_Jump_L" },
      { Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_To_Jump_R"), "Ladder_Look_Back_To_Jump_R" },
      { Animator.StringToHash("Base Layer.PushPull.PushCubeRight_RM"), "PushCubeRight_RM" },
      { Animator.StringToHash("Base Layer.PushPull.PullCube_RM"), "PullCube_RM" },
      { Animator.StringToHash("Base Layer.PushPull.PushCube1_RM"), "PushCube1_RM" },
      { Animator.StringToHash("Base Layer.PushPull.PushCubeIdle1"), "PushCubeIdle1" },
      { Animator.StringToHash("Base Layer.Climb Object.ClimbDown_LeftDirection"), "ClimbDown_LeftDirection" },
      { Animator.StringToHash("Base Layer.Climb Object.ClimbDown_RightDirection"), "ClimbDown_RightDirection" },
      { Animator.StringToHash("Base Layer.Climb Object.ClimbUpObject_Critical"), "ClimbUpObject_Critical" },
      { Animator.StringToHash("Base Layer.Climb Object.ClimbUpObject_Settle"), "ClimbUpObject_Settle" },
      { Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedge_Directly_Critical"), "ClimbLedge_Directly_Critical" },
      { Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedge_OverHead_Hanging"), "ClimbLedge_OverHead_Hanging" },
      { Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedge_Directly_OverHead"), "ClimbLedge_Directly_OverHead" },
      { Animator.StringToHash("Base Layer.Climb Ledge.End ClimbLedge BlendTree"), "End_ClimbLedge_BlendTree" },
      { Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedgeToIdle"), "ClimbLedgeToIdle" },
      { Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedgeToRun"), "ClimbLedgeToRun" },
      { Animator.StringToHash("Base Layer.Jump.IdleJump"), "IdleJump" },
      { Animator.StringToHash("Base Layer.Jump.IdleJump_Landing"), "IdleJump_Landing" },
      { Animator.StringToHash("Base Layer.Jump.RunJump Blend Tree"), "RunJump_Blend_Tree" },
      { Animator.StringToHash("Base Layer.Jump.RunJumpLanding Blend Tree"), "RunJumpLanding_Blend_Tree" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Fall_FromRun"), "Fall_FromRun" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Fall_FromJump"), "Fall_FromJump" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Mini"), "Landing_Mini" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Idle_Soft"), "Landing_Idle_Soft" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Idle_Medium"), "Landing_Idle_Medium" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Idle_Heavy"), "Landing_Idle_Heavy" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Running.Landing_Running_Soft"), "Landing_Running_Soft" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Running.Landing_Running_Medium"), "Landing_Running_Medium" },
      { Animator.StringToHash("Base Layer.Fall-Landing.Landing_Running.Landing_Running_Heavy"), "Landing_Running_Heavy" },
      { Animator.StringToHash("Base Layer.Turn.New State"), "New_State" },
      { Animator.StringToHash("Base Layer.Turn.RunTurn.RunTurn"), "RunTurn" },
      { Animator.StringToHash("Base Layer.Turn.RunTurn.RunTurn_R"), "RunTurn_R" },
      { Animator.StringToHash("Base Layer.Turn.RunTurn.New State"), "New_State" },
      { Animator.StringToHash("Base Layer.Turn.IdleTurn StateMachine.IdleTurn"), "IdleTurn" },
      { Animator.StringToHash("Base Layer.Turn.IdleTurn StateMachine.IdleTurn_R"), "IdleTurn_R" },
      { Animator.StringToHash("Base Layer.Slope.Traversal_Slide_45Degree_Slope_Loop"), "Traversal_Slide_45Degree_Slope_Loop" },
      { Animator.StringToHash("Base Layer.Slope.Traversal_Slide_45Degree_Slope_End"), "Traversal_Slide_45Degree_Slope_End" },
      { Animator.StringToHash("Base Layer.Lever.Activate_Wall_SlideLever_Up"), "Activate_Wall_SlideLever_Up" },
      { Animator.StringToHash("Base Layer.Lever.Activate_Wall_SlideLever_Down"), "Activate_Wall_SlideLever_Down" },
      { Animator.StringToHash("Base Layer.Lever.Activate_Wall_SlideLever_Idle"), "Activate_Wall_SlideLever_Idle" },
      { Animator.StringToHash("Base Layer.Run.Run"), "Run" },
      { Animator.StringToHash("Base Layer.Run.IdleToRun"), "IdleToRun" },
      { Animator.StringToHash("Base Layer.Run.RunToIdle_L"), "RunToIdle_L" },
      { Animator.StringToHash("Base Layer.Run.RunToIdle_R"), "RunToIdle_R" },
      { Animator.StringToHash("Ladder Jump Ready Layer.Traversal_Wall_Climb_LookRight_Loop"), "Traversal_Wall_Climb_LookRight_Loop" },
      { Animator.StringToHash("Ladder Jump Ready Layer.New State"), "New_State" },
      { Animator.StringToHash("Ladder Jump Ready Layer.Traversal_Wall_Climb_LookLeft_Loop"), "Traversal_Wall_Climb_LookLeft_Loop" },
      { Animator.StringToHash("Ladder Jump Ready Layer.A_Run_Down25F_Masc"), "A_Run_Down25F_Masc" },
      { Animator.StringToHash("Run Layer.New State"), "New_State" },
      { Animator.StringToHash("Run Layer.A_Run_Down25F_Masc"), "A_Run_Down25F_Masc" },
   };
}
