// Auto-generated. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

public static class AnimStateHash
{
   public static Dictionary<AnimState, int> stateHashes = new()
   {
      { AnimState.Climb_Rope_With_Legs, Animator.StringToHash("Base Layer.Climb_Rope_With_Legs") },
      { AnimState.Idle, Animator.StringToHash("Base Layer.Idle") },
      { AnimState.FrontWall, Animator.StringToHash("Base Layer.FrontWall") },
      { AnimState.Traversal_Ladder_Climb_Up_Loop, Animator.StringToHash("Base Layer.Ladder.Traversal_Ladder_Climb_Up_Loop") },
      { AnimState.Traversal_Ladder_Climb_Down_Start, Animator.StringToHash("Base Layer.Ladder.Traversal_Ladder_Climb_Down_Start") },
      { AnimState.EndToPlatform, Animator.StringToHash("Base Layer.Ladder.EndToPlatform") },
      { AnimState.EndToPlatfor_Settle, Animator.StringToHash("Base Layer.Ladder.EndToPlatfor Settle") },
      { AnimState.Ladder_ClimbUp, Animator.StringToHash("Base Layer.Ladder.Ladder_ClimbUp") },
      { AnimState.Ladder_Start_From_Top, Animator.StringToHash("Base Layer.Ladder.Ladder_Start_From_Top") },
      { AnimState.Ladder_Look_Back_L, Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_L") },
      { AnimState.Ladder_Look_Back_R, Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_R") },
      { AnimState.Ladder_Look_Back_To_Jump_L, Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_To_Jump_L") },
      { AnimState.Ladder_Look_Back_To_Jump_R, Animator.StringToHash("Base Layer.Ladder.Ladder_Look_Back_To_Jump_R") },
      { AnimState.PushCubeRight_RM, Animator.StringToHash("Base Layer.PushPull.PushCubeRight_RM") },
      { AnimState.PullCube_RM, Animator.StringToHash("Base Layer.PushPull.PullCube_RM") },
      { AnimState.PushCube1_RM, Animator.StringToHash("Base Layer.PushPull.PushCube1_RM") },
      { AnimState.PushCubeIdle1, Animator.StringToHash("Base Layer.PushPull.PushCubeIdle1") },
      { AnimState.ClimbDown_LeftDirection, Animator.StringToHash("Base Layer.Climb Object.ClimbDown_LeftDirection") },
      { AnimState.ClimbDown_RightDirection, Animator.StringToHash("Base Layer.Climb Object.ClimbDown_RightDirection") },
      { AnimState.ClimbUpObject_Critical, Animator.StringToHash("Base Layer.Climb Object.ClimbUpObject_Critical") },
      { AnimState.ClimbUpObject_Settle, Animator.StringToHash("Base Layer.Climb Object.ClimbUpObject_Settle") },
      { AnimState.ClimbLedge_Directly_Critical, Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedge_Directly_Critical") },
      { AnimState.ClimbLedge_OverHead_Hanging, Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedge_OverHead_Hanging") },
      { AnimState.ClimbLedge_Directly_OverHead, Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedge_Directly_OverHead") },
      { AnimState.End_ClimbLedge_BlendTree, Animator.StringToHash("Base Layer.Climb Ledge.End ClimbLedge BlendTree") },
      { AnimState.ClimbLedgeToIdle, Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedgeToIdle") },
      { AnimState.ClimbLedgeToRun, Animator.StringToHash("Base Layer.Climb Ledge.ClimbLedgeToRun") },
      { AnimState.IdleJump, Animator.StringToHash("Base Layer.Jump.IdleJump") },
      { AnimState.IdleJump_Landing, Animator.StringToHash("Base Layer.Jump.IdleJump_Landing") },
      { AnimState.RunJump_Blend_Tree, Animator.StringToHash("Base Layer.Jump.RunJump Blend Tree") },
      { AnimState.RunJumpLanding_Blend_Tree, Animator.StringToHash("Base Layer.Jump.RunJumpLanding Blend Tree") },
      { AnimState.Fall_FromRun, Animator.StringToHash("Base Layer.Fall-Landing.Fall_FromRun") },
      { AnimState.Fall_FromJump, Animator.StringToHash("Base Layer.Fall-Landing.Fall_FromJump") },
      { AnimState.Landing_Mini, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Mini") },
      { AnimState.Landing_Idle_Soft, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Idle_Soft") },
      { AnimState.Landing_Idle_Medium, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Idle_Medium") },
      { AnimState.Landing_Idle_Heavy, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Idle.Landing_Idle_Heavy") },
      { AnimState.Landing_Running_Soft, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Running.Landing_Running_Soft") },
      { AnimState.Landing_Running_Medium, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Running.Landing_Running_Medium") },
      { AnimState.Landing_Running_Heavy, Animator.StringToHash("Base Layer.Fall-Landing.Landing_Running.Landing_Running_Heavy") },
      { AnimState.New_State, Animator.StringToHash("Base Layer.Turn.New State") },
      { AnimState.RunTurn, Animator.StringToHash("Base Layer.Turn.RunTurn.RunTurn") },
      { AnimState.RunTurn_R, Animator.StringToHash("Base Layer.Turn.RunTurn.RunTurn_R") },
      { AnimState.New_State_2, Animator.StringToHash("Base Layer.Turn.RunTurn.New State") },
      { AnimState.IdleTurn, Animator.StringToHash("Base Layer.Turn.IdleTurn StateMachine.IdleTurn") },
      { AnimState.IdleTurn_R, Animator.StringToHash("Base Layer.Turn.IdleTurn StateMachine.IdleTurn_R") },
      { AnimState.Traversal_Slide_45Degree_Slope_Loop, Animator.StringToHash("Base Layer.Slope.Traversal_Slide_45Degree_Slope_Loop") },
      { AnimState.Traversal_Slide_45Degree_Slope_End, Animator.StringToHash("Base Layer.Slope.Traversal_Slide_45Degree_Slope_End") },
      { AnimState.Activate_Wall_SlideLever_Up, Animator.StringToHash("Base Layer.Lever.Activate_Wall_SlideLever_Up") },
      { AnimState.Activate_Wall_SlideLever_Down, Animator.StringToHash("Base Layer.Lever.Activate_Wall_SlideLever_Down") },
      { AnimState.Activate_Wall_SlideLever_Idle, Animator.StringToHash("Base Layer.Lever.Activate_Wall_SlideLever_Idle") },
      { AnimState.Run, Animator.StringToHash("Base Layer.Run.Run") },
      { AnimState.IdleToRun, Animator.StringToHash("Base Layer.Run.IdleToRun") },
      { AnimState.RunToIdle_L, Animator.StringToHash("Base Layer.Run.RunToIdle_L") },
      { AnimState.RunToIdle_R, Animator.StringToHash("Base Layer.Run.RunToIdle_R") },
      { AnimState.Traversal_Wall_Climb_LookRight_Loop, Animator.StringToHash("Ladder Jump Ready Layer.Traversal_Wall_Climb_LookRight_Loop") },
      { AnimState.New_State_3, Animator.StringToHash("Ladder Jump Ready Layer.New State") },
      { AnimState.Traversal_Wall_Climb_LookLeft_Loop, Animator.StringToHash("Ladder Jump Ready Layer.Traversal_Wall_Climb_LookLeft_Loop") },
      { AnimState.A_Run_Down25F_Masc, Animator.StringToHash("Ladder Jump Ready Layer.A_Run_Down25F_Masc") },
      { AnimState.New_State_4, Animator.StringToHash("Run Layer.New State") },
      { AnimState.A_Run_Down25F_Masc_2, Animator.StringToHash("Run Layer.A_Run_Down25F_Masc") },
   };
}
